spring:
  application:
    name: ordderservicexsd
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
server:
  port: 8083
app:
  orders:
    loc: "D://local_pratice//xml_orders_location//"
      
    